### ISSUE TITLE
Document with type=Stream

### ISSUE THREAD

**Issue by deyanp** [Dzoukr/CosmoStore#24]
What is exactly the purpose of the document with type=`Stream`, including `lastPosition`, `lastUpdatedUtc` attribute? Shouldn't it be in another collection?
Btw, what is the partition key of the collection?

**Comment by Dzoukr** [comment]
Hi @deyanp,

PartitionKey is the StreamId. Type=`Stream` is holder of stream metadata and since there is no transactional guarantee across collections, it must be in same Partition and same collection.

**Comment by deyanp** [comment]
Hi @Dzoukr ,

But why do you need that record at all? I assume every time you want to write new events from a certain position, you first read the existing events, including the last event with the last position.  So you can easily take last event's position and compare with the currently expected position, or you can take 0 if no prior events in the database?

**Comment by Dzoukr** [comment]
Hi @deyanp,

reading all events on each insertion could be quite time/resource consuming. Having index of stream stored in different document is not only faster, but also brings possibility to iterate over all streams and find their last position / last update, which could be handy in some scenarios.

Just for me to understand - is there any issue in that?

**Comment by deyanp** [comment]
Hi @Dzoukr,

No issue at all, just trying to fully understand your library, before I start using it in new project at work. 3 questions if I may:
1) The document in question contains only `lastPosition` and `lastUpdatedUtc` attributes - can you tell me when you read/use this document?
2) Do you store snapshots (last stream state) somewhere?
3) You said "reading all events on each insertion could be quite time/resource consuming". My understanding is that you (1) read all events of a stream, (2) materialize the state (3) execute some command against the state and generate events and (4) insert the events. Do you mean sometimes you don't need to go through (1), (2) and (3) but directly go to (4) insert the events?

**Comment by Dzoukr** [comment]
Hi @deyanp ,

1. For example here https://github.com/Dzoukr/CosmoStore/blob/master/src/CosmoStore.TableStorage/EventStore.fs#L31 But as said before - this information could be also handy when you need some kind of overview across whole Event Store.
2. Nope, this should be done by you based on your needs. You can use different stream, memory - whatever fits your application. I wanted to keep this library as simple as possible.
3. Well, as you mentioned in point 2 - there are things like snapshots. If you have snapshot, you don't want to read full stream (that's why you have it). You need index of snapshot and want to read events from index+1 till the end of stream. If this library would re-read all events to get lastPosition, whole snapshotting would be useless. And about state - there is no state from this library point of view. State is in your application. This is just a storage. :)
