### ISSUE TITLE
Why no CausationId?

### ISSUE THREAD

**Issue by lfr** [Dzoukr/CosmoStore#9]
Been reading the doc and I see CorrelationId but no CausationId, is this a deliberate decision? If so, why? Note that it's very likely I would know this if I were more experienced in ES.

**Comment by Dzoukr** [comment]
Hi @lferrao,

no problem at all :) From what I understand the difference between CorrelationId vs CausationId is that CorrelationId lets you to see all related events, where CausationId is the Id of the initial event (that caused new events created).

Since in this library everything is in developer's hands, it is up to you, how you use this field. You can use Id of triggering event as CorrelationId for chained events so initial event Id is the causation one, and chained events can be correlated by that. 

I personally do it rather this way:

1. I have new event to write into store
2. Generate new Guid as CorrelationId
3. Use this CorrelationId for any other events that happened as result of first one
4. Now I have first event + any chained stored under same CorrelationId, so I can see whole conversation.

What do you think about it?

**Comment by Dzoukr** [comment]
I think you got point here - the correlationId is good for grouping related events, but the tree view is missing here. I will think about it for next release, however need to think about it more from two reasons:

- it would be breaking change (or it would have to be optional)
- there is no function for getting events based on correlationId (yet)

**Comment by lfr** [comment]
I realized reading your message that what I said can't be correct. I said
you can get one with the other but in fact without CausationID you can't
tell if two events were caused by the same (parent) event and are in fact
siblings as opposed to all three being caused linearly one after following
another. I mean similar timestamps can indicate it but that's really not a
proper or reliable way to tell. You really need both correlation and
causation as far as I can tell.

**Comment by Dzoukr** [comment]
Yes, that would be handy. I'll think about it for new version definitely.

**Comment by Dzoukr** [comment]
FYI, I am about to release version 2 soon (tomorrow or day after tomorrow most likely) with having both CorrelationId & CausationId. Also from v2.0.0 each CosmoStore implementation will be in separate package where `CosmoStore` is only API definition.

* https://www.nuget.org/packages/CosmoStore/2.0.0-beta1
* https://www.nuget.org/packages/CosmoStore.TableStorage/2.0.0-beta1
* https://www.nuget.org/packages/CosmoStore.CosmosDb/2.0.0-beta1

**Comment by lfr** [comment]
That's pretty awesome! Unfortunately for me, I had to stick with Postgres for the backing store along with some additional weird requirements like having to rely on FSharpLu's serialization, so I ended up writing my own poor man's store that's clearly never meant to be battle-ready, but I did use the opportunity (if it can be calle that) to familiarize myself with CQRS.

**Comment by Dzoukr** [comment]
No problem, the `CosmoStore.Postgres` will be probably the next package 😄

**Comment by Dzoukr** [comment]
Aaaaaaaaaaaand it is published and docs updated. Thanks for hints! 🙏
